import {StyleSheet} from 'react-native';
import {Colors} from '../../config/colors';

export const styles = StyleSheet.create({
  Container: {
    flex: 1,
    backgroundColor: Colors.grayDark,
  },
  Header: {
    backgroundColor: Colors.grayDark,
    height: 50,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  HeaderLogo: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  Logo: {
    color: Colors.red,
    left: 5,
  },
  TextLogo: {
    left: 11,
    fontSize: 18,
    fontFamily: 'Roboto',
    fontWeight: 'bold',
    color: Colors.white,
  },
  HeaderIcons: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  Icon: {
    color: Colors.white,
    padding: 10,
  },
  Img: {
    height: 30,
    width: 30,
    borderRadius: 15,
    right: 3,
  },
  Category: {
    flexDirection: 'row',
    backgroundColor: Colors.grayDarkHeader,
  },
  CategoryColumn: {
    margin: 5,
    flexDirection: 'column',
  },
  LabelBooming: {
    flexDirection: 'row',
    alignItems: 'center',
    height: 45,
    width: 175,
    borderRadius: 5,
    backgroundColor: Colors.redLabel,
    margin: 5,
  },
  LabelGames: {
    flexDirection: 'row',
    alignItems: 'center',
    height: 45,
    width: 175,
    borderRadius: 5,
    backgroundColor: Colors.DarkSalmon,
    margin: 5,
  },
  LabelMoves: {
    flexDirection: 'row',
    alignItems: 'center',
    height: 45,
    width: 175,
    borderRadius: 5,
    backgroundColor: Colors.Gold,
    margin: 5,
  },
  LabelLive: {
    flexDirection: 'row',
    alignItems: 'center',
    height: 45,
    width: 175,
    borderRadius: 5,
    backgroundColor: Colors.DarkOrange,
    margin: 5,
  },
  LabelMusic: {
    flexDirection: 'row',
    alignItems: 'center',
    height: 45,
    width: 175,
    borderRadius: 5,
    backgroundColor: Colors.Cyan,
    margin: 5,
  },
  LabelNews: {
    flexDirection: 'row',
    alignItems: 'center',
    height: 45,
    width: 175,
    borderRadius: 5,
    backgroundColor: Colors.Blue,
    margin: 5,
  },
  LabelLearn: {
    flexDirection: 'row',
    alignItems: 'center',
    height: 45,
    width: 175,
    borderRadius: 5,
    backgroundColor: Colors.Green,
    margin: 5,
  },
  TextLabel: {
    color: Colors.white,
    fontSize: 16,
    fontWeight: 'bold',
  },
});
