import {StyleSheet} from 'react-native';
import {Colors} from '../../config/colors';

export const styles = StyleSheet.create({
  Container: {
    flex: 1,
    backgroundColor: Colors.grayDark,
  },
  CanalPerfiel: {
    margin: 5,
    height: 40,
    width: 40,
    borderRadius: 20,
  },
  Header: {
    backgroundColor: Colors.grayDark,
    height: 50,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  HeaderLogo: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  Logo: {
    color: Colors.red,
    left: 5,
  },
  TextLogo: {
    left: 11,
    fontSize: 18,
    fontFamily: 'Roboto',
    fontWeight: 'bold',
    color: Colors.white,
  },
  HeaderIcons: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  Icon: {
    color: Colors.white,
    padding: 10,
  },
  Img: {
    height: 30,
    width: 30,
    borderRadius: 15,
    right: 3,
  },
  Category: {
    flexDirection: 'row',
    backgroundColor: Colors.grayDarkHeader,
  },
  CategoryColumn: {
    margin: 5,
    flexDirection: 'column',
  },
  LabelBooming: {
    flexDirection: 'row',
    alignItems: 'center',
    height: 45,
    width: 175,
    borderRadius: 5,
    backgroundColor: Colors.redLabel,
    margin: 5,
  },
  LabelGames: {
    flexDirection: 'row',
    alignItems: 'center',
    height: 45,
    width: 175,
    borderRadius: 5,
    backgroundColor: Colors.DarkSalmon,
    margin: 5,
  },
  LabelMoves: {
    flexDirection: 'row',
    alignItems: 'center',
    height: 45,
    width: 175,
    borderRadius: 5,
    backgroundColor: Colors.Gold,
    margin: 5,
  },
  LabelLive: {
    flexDirection: 'row',
    alignItems: 'center',
    height: 45,
    width: 175,
    borderRadius: 5,
    backgroundColor: Colors.DarkOrange,
    margin: 5,
  },
  LabelMusic: {
    flexDirection: 'row',
    alignItems: 'center',
    height: 45,
    width: 175,
    borderRadius: 5,
    backgroundColor: Colors.Cyan,
    margin: 5,
  },
  LabelNews: {
    flexDirection: 'row',
    alignItems: 'center',
    height: 45,
    width: 175,
    borderRadius: 5,
    backgroundColor: Colors.Blue,
    margin: 5,
  },
  LabelLearn: {
    flexDirection: 'row',
    alignItems: 'center',
    height: 45,
    width: 175,
    borderRadius: 5,
    backgroundColor: Colors.Green,
    margin: 5,
  },
  LabelSports: {
    flexDirection: 'row',
    alignItems: 'center',
    height: 45,
    width: 175,
    borderRadius: 5,
    backgroundColor: Colors.DodgerBlue,
    margin: 5,
  },
  TextLabel: {
    color: Colors.white,
    fontSize: 16,
    fontWeight: 'bold',
  },
  TabGraySmall: {
    marginTop: 2,
    marginBottom: 10,
    borderBottomColor: Colors.grayLight,
    borderBottomWidth: 2,
  },
  FBreederContainer: {},
  FeaturedBreeder: {
    flexDirection: 'row',
  },
  NameCh: {
    margin: 2,
    color: Colors.white,
    fontSize: 16,
    fontWeight: 'bold',
  },
  BorderColor: {
    width: 130,
    height: 15,
    borderRadius: 5,
    backgroundColor: Colors.Blue,
    alignItems: 'center',
  },
  TextFBreeder: {
    color: Colors.white,
    fontSize: 12,
    fontWeight: 'bold',
  },
  ScrollView: {
    marginBottom: 2,
  },
  MiniLabel: {
    margin: 5,
    width: 180,
    height: 160,
    borderRadius: 5,
    alignItems: 'center',
  },
  Layer: {},
  TextPosition: {
    alignItems: 'center',
  },
  shortText: {
    fontSize: 18,
    fontFamily: 'Roboto',
    fontWeight: 'bold',
    color: Colors.white,
    marginBottom: 10,
    marginLeft: 10,
  },
});
